export function dashboardHtml(token: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="swarmwatch-token" content="${token}"><title>SwarmWatch</title>
<style>
:root{color-scheme:dark;--bg:#05070d;--panel:#0b1220;--line:#1c355f;--text:#d9f1ff;--muted:#7aa7c7;--cyan:#42e8ff;--red:#ff3864;--amber:#ffcf5a;--green:#6dff9b}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#142648,#05070d 40%,#02030a);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:var(--text)}header{display:flex;align-items:center;justify-content:space-between;padding:18px 22px;border-bottom:1px solid var(--line);background:#05070dbb;position:sticky;top:0;backdrop-filter:blur(10px)}h1{margin:0;color:var(--cyan);letter-spacing:.15em;text-shadow:0 0 18px #42e8ff77}.grid{display:grid;grid-template-columns:1fr 380px;gap:16px;padding:16px}.panel{background:linear-gradient(180deg,#0b1220dd,#070c16ee);border:1px solid var(--line);box-shadow:0 0 24px #006bff1f;border-radius:14px;padding:14px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{border:1px solid #1a3a68;border-radius:12px;padding:12px;background:#07111f}.stat b{display:block;font-size:28px;color:var(--cyan)}#map{height:520px;position:relative;overflow:hidden;background:radial-gradient(circle,#10213d,#050914);border-radius:14px}.node{position:absolute;min-width:140px;border:1px solid var(--cyan);border-radius:12px;padding:10px;background:#06101fcc;box-shadow:0 0 18px #42e8ff44;transform:translate(-50%,-50%)}.node.done{border-color:var(--green)}.node.error,.node.killed{border-color:var(--red)}.node small{color:var(--muted)}.edge{position:absolute;height:2px;background:linear-gradient(90deg,transparent,var(--cyan),transparent);transform-origin:left center;opacity:.7;animation:pulse 1.2s infinite}@keyframes pulse{50%{opacity:.2}}.alert{border-left:4px solid var(--amber);padding:10px;margin:10px 0;background:#201707;border-radius:8px}.alert.critical{border-color:var(--red);background:#240511}.kill{background:var(--red);color:white;border:0;padding:5px 8px;border-radius:6px;cursor:pointer}.events{max-height:230px;overflow:auto;color:var(--muted);font-size:12px}code{color:var(--green)}@media(max-width:900px){.grid{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}}</style></head>
<body><header><h1>SWARMWATCH</h1><div id="clock"></div></header><main class="grid"><section><div class="stats"><div class="stat">Agents<b id="agents">0</b></div><div class="stat">Running<b id="running">0</b></div><div class="stat">Cost<b id="cost">$0</b></div><div class="stat">Alerts<b id="alerts">0</b></div></div><div class="panel" style="margin-top:16px"><h2>Topology</h2><div id="map"></div></div></section><aside><div class="panel"><h2>Drift alarms</h2><div id="alertList"></div></div><div class="panel" style="margin-top:16px"><h2>API</h2><p><code>GET /api/state</code></p><p><code>POST /api/events</code></p><p><code>POST /api/kill/:agent</code></p></div><div class="panel" style="margin-top:16px"><h2>Recent agents</h2><div id="events" class="events"></div></div></aside></main>
<script>
const token=document.querySelector('meta[name="swarmwatch-token"]').content;
function cls(v,allowed,fallback){return allowed.includes(v)?v:fallback}
function el(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=String(text);return e}
function clear(e){while(e.firstChild)e.removeChild(e.firstChild)}
function pos(i,n){const cx=50,cy=50,a=(Math.PI*2*i/Math.max(n,1))-Math.PI/2;return [cx+Math.cos(a)*38,cy+Math.sin(a)*38]}
async function killAgent(id){await fetch('/api/kill/'+encodeURIComponent(id),{method:'POST',headers:{'x-swarmwatch-token':token}});await tick()}
function drawAlerts(list){clear(alertList);if(!list.length){alertList.appendChild(el('p','', 'No alarms.'));return;}for(const a of list){const box=el('div','alert '+cls(a.severity,['info','warn','critical'],'warn'));box.appendChild(el('b','',a.kind));box.appendChild(document.createElement('br'));box.appendChild(document.createTextNode(a.message));alertList.appendChild(box)}}
function drawRecent(list){clear(events);for(const a of list){const p=el('p');p.appendChild(el('b','',a.id));p.appendChild(document.createTextNode(' '+a.status+' · $'+a.costUsd.toFixed(4)+' · '+(a.lastMessage||'')));events.appendChild(p)}}
function draw(s){clock.textContent=new Date(s.generatedAt).toLocaleTimeString();agents.textContent=s.totals.agents;running.textContent=s.totals.running;cost.textContent='$'+s.totals.costUsd.toFixed(4);alerts.textContent=s.alerts.length;drawAlerts(s.alerts);drawRecent(s.agents);const m=document.getElementById('map');clear(m);const ps=new Map();s.agents.forEach((a,i)=>{const p=pos(i,s.agents.length);ps.set(a.id,p)});s.edges.forEach(e=>{const a=ps.get(e.from),b=ps.get(e.to);if(!a||!b)return;const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx);const line=el('div','edge');line.style.left=a[0]+'%';line.style.top=a[1]+'%';line.style.width=len+'%';line.style.transform='rotate('+ang+'rad)';m.appendChild(line)});s.agents.forEach((a)=>{const p=ps.get(a.id);const node=el('div','node '+cls(a.status,['running','done','error','killed','unknown'],'unknown'));node.style.left=p[0]+'%';node.style.top=p[1]+'%';node.appendChild(el('b','',a.id));node.appendChild(document.createElement('br'));node.appendChild(el('small','',a.framework+' · '+a.status));node.appendChild(document.createElement('br'));node.appendChild(el('small','','$'+a.costUsd.toFixed(4)+' · '+a.toolCalls+' tools'));node.appendChild(document.createElement('br'));const button=el('button','kill','KILL');button.addEventListener('click',()=>killAgent(a.id));node.appendChild(button);m.appendChild(node)})}
async function tick(){try{const r=await fetch('/api/state');draw(await r.json())}catch(e){console.error(e)}}tick();setInterval(tick,1500)
</script></body></html>`;
}
